config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users.views import CustomPasswordChangeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('place.urls')), # place앱
    path('', include('users.urls')),
    path('', include('allauth.urls')), #allauth앱
    path(
        'email-confirmation-required/',
        TemplateView.as_view(template_name='account/email_confirmation_required.html'),
        name='account_email_confirmation_required',
    ),
    path(
        'email-confirmation-done/',
        TemplateView.as_view(template_name='account/email_confirmation_done.html'),
        name='account_email_confirmation_done',
    ),
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

place/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'place'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('place/detail/'), # 플레이스 리스트
    path('place/detail/<int:restaurant_id>/', views.PlaceDetailView.as_view(), name='place-detail')
]

place/models.py
from django.db import models


# Create your models here.
class Restaurant(models.Model):
    res_name = models.CharField(max_length=100)
    res_address = models.CharField(max_length=100)
    res_road_address = models.CharField(max_length=100)
    res_tel = models.CharField(max_length=30, blank=True, null=True)
    res_link = models.URLField(null=True, blank=True)
    res_stars = models.FloatField(null=True, blank=True)
    res_summary = models.CharField(max_length=200, null=True, blank=True)
    res_description = models.TextField(null=True, blank=True)
    res_find = models.CharField(max_length=200, null=True, blank=True)
    res_payment = models.CharField(max_length=50, null=True, blank=True)
    res_comfortables = models.CharField(max_length=200, null=True, blank=True)
    res_thumbnail = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    res_sub_thumbnail1 = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    res_sub_thumbnail2 = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    res_sub_thumbnail3 = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    def __str__(self):
        return self.res_name

class Menu(models.Model):
    menu_fk = models.OneToOneField(Restaurant, on_delete=models.CASCADE)
    menu = models.JSONField(null=True)

    def __str__(self):
        return 'menu'
    
class Store(models.Model):
    store_id = models.AutoField(primary_key=True) # store_id
    site= models.TextField(null=True)
    site_id = models.IntegerField(unique=True)
    store_name= models.TextField(null=True)
    micro_review= models.TextField(null=True)
    avg_rating= models.FloatField(null=True)
    main_image_url= models.TextField(null=True)
    tel= models.TextField()
    thumbnail = models.TextField(null=True)
    address = models.TextField(null=True)
    road_address = models.TextField(null=True)
    abbr_address = models.TextField(null=True)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    visit_review_count = models.IntegerField(null=True)
    blog_review_count = models.IntegerField(null=True)
    biz_hour_info = models.TextField(null=True)
    create_date = models.DateField(null=True)
    def __str__(self):
        return self.store_name
    
  
class Store_menu(models.Model):
    menu_id = models.BigAutoField(primary_key=True)
    menu_name= models.TextField(null=True)
    menu_price= models.IntegerField(null=True)
    menu_image= models.TextField(null=True)
    menu_desc= models.TextField(null=True)
    store= models.ForeignKey(Store, to_field='site_id', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.menu_name
# class BusinessHour(models.Model):
#     fk = models.OneToOne
    


class Category(models.Model):
    category = models.TextField()
    sub_category = models.TextField()
    def _str_(self):
        return self.category

place/views.py
from django.shortcuts import render
from django.http import Http404
from django.views.generic import (
    View,
    ListView, 
    DetailView, 
    CreateView, 
    UpdateView, 
    DeleteView
)


from .models import *

class IndexView(View):
    def get(self, request, *args, **kwargs):
        main = Restaurant.objects.all().order_by('id')[:4]
        store = Store.objects.all()
        store_menu = Store_menu.objects.all()
        star = []
        for i in main.values():
            try:
                num = int(i['res_stars'])
                point = float(i['res_stars']) - num
                ls = [1 for _ in range(num)]
                if (point >= 0.25) and (point < 0.99):
                    ls.append(2)
                elif point < 0.25:
                    ls.append(0)
                if len(ls) != 5:
                    for _ in range(5-len(ls)):
                        ls.append(0)
                star.append({'name': i['id'], 'star': ls})
            except:
                star.append({'name': i['id'], 'star': [0, 0, 0, 0, 0]})


        context = {'main': main, 'star': star,'store':store,'store_menu':store_menu}
        return render(request, 'place/index.html', context)

class PlaceDetailView(View):
    def get(self, request, restaurant_id, *args, **kwargs):
        try:
            place = Restaurant.objects.get(id=restaurant_id)
            menu = Menu.objects.get(id=restaurant_id)

        except Restaurant.DoesNotExist:
            raise Http404('장소가 존재하지 않아요')

        return render(request, 'place/place_detail.html', context={'place':place, 'menu':menu})
    # def get(self, request, *args, **kwargs):
    #     menu = Menu.object.get(id=restaurant_id)

    # def book_detail_view(request, primary_key):
    # try:
    #     book = Book.objects.get(pk=primary_key)
    # except Book.DoesNotExist:
    #     raise Http404('Book does not exist')

    # return render(request, 'catalog/book_detail.html', context={'book': book})

place/templates/place/index.html
{% extends 'place_base/base.html' %}
{% block main_area %}

<!--===============================
=            Hero Area            =
================================-->
<section class="hero-area bg-1 text-center overly">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- Header Contetnt -->
				<div class="content-block">
					<h1>야미</h1>
					<p>오늘 뭐먹지 고민하지말고 찾아보세요</p>
					<div class="short-popular-category-list text-center">
						<h2>Popular Category</h2>
						<ul class="list-inline">
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-bed"></i> Hotel</a></li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-grav"></i> Fitness</a>
							</li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-car"></i> Cars</a>
							</li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-cutlery"></i> Restaurants</a>
							</li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-coffee"></i> Cafe</a>
							</li>
						</ul>
					</div>

				</div>
				<!-- Advance Search -->
				<div class="advance-search">
					<div class="container">
						<div class="row justify-content-center">
							<div class="col-lg-12 col-md-12 align-content-center">
								<form>
									<div class="form-row">
                                        <div class="form-group col-lg-3 col-md-6">
											<select class="w-100 form-control mt-lg-1 mt-md-2" aria-placeholder="카레고리">
												<option selected disabled>카테고리</option>
												<option value="1">한식</option>
												<option value="2">일식</option>
												<option value="3">중식</option>
											</select>
										</div>
                                        <div class="form-group col-lg-3 col-md-6">
											<input type="text" class="form-control my-2 my-lg-1" id="inputLocation4" placeholder="위치">
										</div>
										<div class="form-group col-xl-4 col-lg-3 col-md-6">
											<input type="text" class="form-control my-2 my-lg-1" id="inputtext4"
												placeholder="오늘 뭐먹지?">
										</div>
										<div class="form-group col-xl-2 col-lg-3 col-md-6 align-self-center">
											<button type="submit" class="btn btn-primary active w-100">검색</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>


<!--===========================================
=            Popular deals section            =
============================================-->
<section class="popular-deals section bg-gray">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h2>핫플레이스{{store.site}}</h2>
					<p>뜨고 있는 맛집들</p>
				</div>
			</div>
		</div>
		
		<div class="row">
			<div class="col-lg-12">
				<div class="trending-ads-slide">
					{% for i in main %}
					<div class="col-sm-12 col-lg-4">
						<!-- product card -->
						<div class="product-item bg-light">
							<div class="card">
								<div class="thumb-content">
									<a href="{% url 'place:place-detail' i.id %}">
									<img class="card-img-top img-fluid" src="/media/{{i.res_thumbnail}}" alt="Card image cap">
									</a>
								</div>
								<div class="card-body">
									<h4 class="card-title"><a href="{% url 'place:place-detail' i.id %}">{{ i.res_name }}</a></h4>
									<ul class="list-inline product-meta">
										<li class="list-inline-item">
											<a href="single.html"><i class="fa fa-check"></i>준비중</a>
										</li>
										<li class="list-inline-item">
											<a href="category.html"><i class="fa fa-check"></i>준비중</a>
										</li>
									</ul>
									{% if i.res_summary != '' %}
										<p class="card-text">{{ i.res_summary }}</p>
									{% else %}
									<p class="card-text">설명 준비중</p>
									{% endif %}
									<div class="product-ratings">
										<ul class="list-inline">
											{% for j in star %}
												{% if j.name == i.id %}
													{% for k in j.star %}
														{% if k == 0 %}
															<li class="list-inline-item"><i class="fa fa-star"></i></li>
														{% endif %}
														{% if k == 1 %}
															<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
														{% endif %}
														{% if k == 2 %}
															<li class="list-inline-item selected"><i class="fa fa-star-half"></i></li>
														{% endif %}
													{% endfor %}
												{% endif %}
											{% endfor %}
											{% if i.res_stars != None %}
												<li class="list-inline-item selected">{{i.res_stars}}</li>
											{% endif %}
										
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
					
				</div>
			</div>
		</div>
	</div>
</section>



<!--==========================================
=            All Category Section            =
===========================================-->

<section class=" section">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Section title -->
				<div class="section-title">
					<h2>카테고리 전체 보기</h2>
					<p>골라보세요~</p>
				</div>
				<div class="row">
					{{ categories.test }}
					<br><br>
					<!-- Category list -->
					{% for category in categories.main_category_name %}
					<div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6">
						<div class="category-block">
							<div class="header">
								<i class="fa fa-laptop icon-bg-1"></i>
								<h4>{{ category.main_category }}</h4>
							</div>

							<ul class="category-list">
								<li><a href="category.html">Laptops <span>93</span></a></li>
								<li><a href="category.html">Iphone <span>233</span></a></li>
								<li><a href="category.html">Microsoft <span>183</span></a></li>
								<li><a href="category.html">Monitors <span>343</span></a></li>
							</ul>

						</div>
					</div> <!-- /Category List -->
					{% endfor %}
					<!-- Category list -->
					<div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6">
						<div class="category-block">
							<div class="header">
								<i class="fa fa-apple icon-bg-2"></i>
								<h4>Restaurants</h4>
							</div>
							<ul class="category-list">
								<li><a href="category.html">Cafe <span>393</span></a></li>
								<li><a href="category.html">Fast food <span>23</span></a></li>
								<li><a href="category.html">Restaurants <span>13</span></a></li>
								<li><a href="category.html">Food Track<span>43</span></a></li>
							</ul>
						</div>
					</div> <!-- /Category List -->
					


				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>

{% endblock %}

place/templates/place/place_detail.html
{% extends 'place_base/base.html' %}
{% block main_area %}

<!--=================================
=            Single Blog            =
==================================-->


<section class="blog single-blog section">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<article class="single-post">
					<h1 style="margin-bottom: 1rem;">{{ place.res_name }}</h1>

					<table class="table border-info">
						<tr>
							<th rowspan="2">주소</th>
							<td>{{place.res_road_address}}</td>
						</tr>
						<tr>
							<td><i class="fa fa-building"></i>&nbsp;{{ place.res_address}}</td>
						</tr>
						<tr>
							<th>전화번호</th>
							<td>{{ place.res_tel }}</td>
						</tr>
						<tr>
							<th>편의사항</th>
							<td>{{ place.res_comfortables}}</td>
						</tr>
					
						<tr>
							<th>웹사이트</th>
							<td><a href="{{place.res_link}}">식당 홈페이지</a></td>
						</tr></table>
					<table class="table border-info">
	
						<tr>
							<th>영업시간</th>
							<td>None</td>
						</tr>
						<tr>
							<th>메뉴</th>
							<td colspan="2">
		

		


							</td>
						</tr>
					</table>
					<br>
					<p style="font-weight: 500; color: #000000; font-size: 1rem">{{ place.res_description}}</p>
				</article>
				
					
				

			
				<div class="block comment">
					<h4>Leave A Comment</h4>
					<form action="#">
						<!-- Message -->
						<div class="form-group mb-30">
							<label for="message">Message</label>
							<textarea class="form-control" id="message" rows="8" required></textarea>
						</div>
						<div class="row">
							<div class="col-sm-12 col-md-6">
								<!-- Name -->
								<div class="form-group mb-30">
									<label for="name">Name</label>
									<input type="text" class="form-control" id="name" required>
								</div>
							</div>
							<div class="col-sm-12 col-md-6">
								<!-- Email -->
								<div class="form-group mb-30">
									<label for="email">Email</label>
									<input type="email" class="form-control" id="email" required>
								</div>
							</div>
						</div>
						<button class="btn btn-transparent">Leave Comment</button>
					</form>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="sidebar">
					<!-- Search Widget -->
					<div class="widget search p-0">
						<div class="input-group">
							<input type="text" class="form-control" id="expire" placeholder="Search...">
							<span class="input-group-addon"><i class="fa fa-search px-3"></i></span>
						</div>
					</div>
					<!-- Category Widget -->
					<div class="widget category">
						<!-- Widget Header -->
						<h5 class="widget-header">Categories</h5>
						<ul class="category-list">
							<li><a href="category.html">Appearel <span class="float-right">(2)</span></a></li>
							<li><a href="category.html">Accesories <span class="float-right">(5)</span></a></li>
							<li><a href="category.html">Business<span class="float-right">(7)</span></a></li>
							<li><a href="category.html">Entertaiment<span class="float-right">(3)</span></a></li>
							<li><a href="category.html">Education<span class="float-right">(9)</span></a></li>
						</ul>
					</div>
					<!-- Archive Widget -->
					<div class="widget archive">
						<!-- Widget Header -->
						<h5 class="widget-header">Archives</h5>
						<ul class="archive-list">
							<li><a href="ad-list-view.html">January 2017</a></li>
							<li><a href="ad-list-view.html">February 2017</a></li>
							<li><a href="ad-list-view.html">March 2017</a></li>
							<li><a href="ad-list-view.html">April 2017</a></li>
							<li><a href="ad-list-view.html">May 2017</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

place/templates/place/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% for i in%}
    <a href="{% url 'place:place-detail' i.id %}">
        <img class="card-img-top img-fluid" src="{{store_menu.menu_image}}" alt="Card image cap">
       
    </a>
</body>
</html>