config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users.views import CustomPasswordChangeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('place.urls')), # place앱
    path('', include('users.urls')),
    path('', include('allauth.urls')), #allauth앱
    path(
        'email-confirmation-required/',
        TemplateView.as_view(template_name='account/email_confirmation_required.html'),
        name='account_email_confirmation_required',
    ),
    path(
        'email-confirmation-done/',
        TemplateView.as_view(template_name='account/email_confirmation_done.html'),
        name='account_email_confirmation_done',
    ),
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

place/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'place'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('place/detail/'), # 플레이스 리스트
    path('place/detail/<int:restaurant_id>/', views.PlaceDetailView.as_view(), name='place-detail')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # User
    path('login/', views.user_login, name='user-login'),
    path('signup/', views.user_signup, name='user-signup'),
    # path('logout/', )
    # review
    # path('', views.IndexView.as_view(), name='index'),
    path('reviews/', views.ReviewListView.as_view(), name='review-list'),
    path('reviews/<int:review_id>/', views.ReviewDetailView.as_view(), name='review-detail'),
    path('reviews/new/', views.ReviewCreateView.as_view(), name='review-create'),
    path('reviews/<int:review_id>/edit/', views.ReviewUpdateView.as_view(), name='review-update'),
    path('reviews/<int:review_id>/delete/', views.ReviewDeleteView.as_view(), name='review-delete'),

    # profile
    path('users/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    path('users/<int:user_id>/reviews/', views.UserReviewListView.as_view(), name='user-review-list'),
    path('set-profile/', views.ProfileSetView.as_view(), name='profile-set'),
    path('edit-profile/', views.ProfileUpdateView.as_view(), name='profile-update'),
]

place/models.py
from django.db import models


# Create your models here.
class Restaurant(models.Model):
    res_name = models.CharField(max_length=100)
    res_address = models.CharField(max_length=100)
    res_road_address = models.CharField(max_length=100)
    res_tel = models.CharField(max_length=30, blank=True, null=True)
    res_link = models.URLField(null=True, blank=True)
    res_stars = models.FloatField(null=True, blank=True)
    res_summary = models.CharField(max_length=200, null=True, blank=True)
    res_description = models.TextField(null=True, blank=True)
    res_find = models.CharField(max_length=200, null=True, blank=True)
    res_payment = models.CharField(max_length=50, null=True, blank=True)
    res_comfortables = models.CharField(max_length=200, null=True, blank=True)
    res_thumbnail = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    res_sub_thumbnail1 = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    res_sub_thumbnail2 = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    res_sub_thumbnail3 = models.ImageField(upload_to='images/restaurant', blank=True, null=True)
    def __str__(self):
        return self.res_name

class Menu(models.Model):
    menu_fk = models.OneToOneField(Restaurant, on_delete=models.CASCADE)
    menu = models.JSONField(null=True)

    def __str__(self):
        return 'menu'
    
class Store(models.Model):
    store_id = models.AutoField(primary_key=True) # store_id
    site= models.TextField(null=True)
    site_id = models.IntegerField(unique=True)
    store_name= models.TextField(null=True)
    micro_review= models.TextField(null=True)
    avg_rating= models.FloatField(null=True)
    main_image_url= models.TextField(null=True)
    tel= models.TextField()
    thumbnail = models.TextField(null=True)
    address = models.TextField(null=True)
    road_address = models.TextField(null=True)
    abbr_address = models.TextField(null=True)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    visit_review_count = models.IntegerField(null=True)
    blog_review_count = models.IntegerField(null=True)
    biz_hour_info = models.TextField(null=True)
    create_date = models.DateField(null=True)
    def __str__(self):
        return self.store_name
    
  
class Store_menu(models.Model):
    menu_id = models.BigAutoField(primary_key=True)
    menu_name= models.TextField(null=True)
    menu_price= models.IntegerField(null=True)
    menu_image= models.TextField(null=True)
    menu_desc= models.TextField(null=True)
    store= models.ForeignKey(Store, to_field='site_id', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.menu_name
# class BusinessHour(models.Model):
#     fk = models.OneToOne
    


class Category(models.Model):
    category = models.TextField()
    sub_category = models.TextField()
    def _str_(self):
        return self.category

place/views.py
from django.shortcuts import render
from django.http import Http404
from django.views.generic import (
    View,
    ListView, 
    DetailView, 
    CreateView, 
    UpdateView, 
    DeleteView
)


from .models import *

class IndexView(View):
    def get(self, request, *args, **kwargs):
        main = Restaurant.objects.all().order_by('id')[:4]
        store = Store.objects.all()
        store_menu = Store_menu.objects.all()
        star = []
        for i in main.values():
            try:
                num = int(i['res_stars'])
                point = float(i['res_stars']) - num
                ls = [1 for _ in range(num)]
                if (point >= 0.25) and (point < 0.99):
                    ls.append(2)
                elif point < 0.25:
                    ls.append(0)
                if len(ls) != 5:
                    for _ in range(5-len(ls)):
                        ls.append(0)
                star.append({'name': i['id'], 'star': ls})
            except:
                star.append({'name': i['id'], 'star': [0, 0, 0, 0, 0]})


        context = {'main': main, 'star': star,'store':store,'store_menu':store_menu}
        return render(request, 'place/index.html', context)

class PlaceDetailView(View):
    def get(self, request, restaurant_id, *args, **kwargs):
        try:
            place = Restaurant.objects.get(id=restaurant_id)
            menu = Menu.objects.get(id=restaurant_id)

        except Restaurant.DoesNotExist:
            raise Http404('장소가 존재하지 않아요')

        return render(request, 'place/place_detail.html', context={'place':place, 'menu':menu})
    # def get(self, request, *args, **kwargs):
    #     menu = Menu.object.get(id=restaurant_id)

    # def book_detail_view(request, primary_key):
    # try:
    #     book = Book.objects.get(pk=primary_key)
    # except Book.DoesNotExist:
    #     raise Http404('Book does not exist')

    # return render(request, 'catalog/book_detail.html', context={'book': book})

place/templates/place_base/base.html
{% load static %}
<!DOCTYPE html>
<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->
<html lang="ko">
<head>
  <!-- ** Basic Page Needs ** -->
  <meta charset="utf-8">
  <title>맛집</title>
  <!-- ** Mobile Specific Metas ** -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Agency HTML Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Classified Marketplace Template v1.0">
  
  <!-- theme meta -->
  <meta name="theme-name" content="classimax" />

  <!-- favicon -->
  <link href="{% static 'place/images/favicon.png' %}" rel="shortcut icon">

  <!-- 
  Essential stylesheets
  =====================================-->
  <link href="{% static 'place/plugin/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'place/plugin/bootstrap/bootstrap-slider.css' %}" rel="stylesheet">
  <link href="{% static 'place/plugin/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'place/plugin/slick/slick.css' %}" rel="stylesheet">
  <link href="{% static 'place/plugin/slick/slick-theme.css' %}" rel="stylesheet">
  <link href="{% static 'place/plugin/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
  
  <link href="{% static 'place/css/style.css' %}" rel="stylesheet">

    <!-- 커스텀 스타일 -->
    <style>
        .card img {
            height: 20rem;
        }
        .bg-1 {
            background: url("{% static 'place/images/home/food.gif' %}");
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>

</head>

<body class="body-wrapper">


<header>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
                {% include 'place_base/navbar.html' %}
			</div>
		</div>
	</div>
</header>

{% block main_area %}
{% endblock %}



<!-- Footer Bottom -->
{% include 'place_base/footer.html' %}

<!-- 
Essential Scripts
=====================================-->
<script src="{% static 'place/plugin/jquery/jquery.min.js' %}"></script>
<script src="{% static 'place/plugin/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'place/plugin/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'place/plugin/bootstrap/bootstrap-slider.js' %}"></script>
<script src="{% static 'place/plugin/tether/js/tether.min.js' %}"></script>
<script src="{% static 'place/plugin/raty/jquery.raty-fa.js' %}"></script>
<script src="{% static 'place/plugin/slick/slick.min.js' %}"></script>
<script src="{% static 'place/plugin/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU" defer></script>
<script src="{% static 'place/plugin/google-map/map.js' %}" defer></script>

<script src="{% static 'place/js/script.js' %}"></script>

</body>

</html>

place/templates/place_base/footer.html
<!-- Footer Bottom -->
<footer class="footer-bottom">
    <!-- Container Start -->
    <div class="container mt-5 mb-5">
      <div class="row">
        <div class="col-lg-6 text-center text-lg-left mb-3 mb-lg-0">
          <!-- Copyright -->
          <div class="copyright">
            <p>Copyright &copy; <script>
                var CurrentYear = new Date().getFullYear()
                document.write(CurrentYear)
              </script>. cccr team3
              <br>Designed & Developed by <a class="text-white" href="https://themefisher.com">Themefisher</a></p>
          </div>
        </div>
        <div class="col-lg-6">
          <!-- Social Icons -->
          <ul class="social-media-icons text-center text-lg-right">
            <li><a class="fa fa-facebook" href="https://www.facebook.com/themefisher"></a></li>
            <li><a class="fa fa-twitter" href="https://www.twitter.com/themefisher"></a></li>
            <li><a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher"></a></li>
            <li><a class="fa fa-github-alt" href="https://www.github.com/themefisher"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Container End -->
    <!-- To Top -->
    <div class="scroll-top-to">
      <i class="fa fa-angle-up"></i>
    </div>
  </footer>

place/templates/place_base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light navigation">
    <a class="navbar-brand" href="{% url 'place:index' %}">
        <img style="height:70px; width:130px;" src="{% static 'place/images/logos.jpg' %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
     aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto main-nav ">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'place:index' %}">홈</a>
            </li>
            <li class="nav-item dropdown dropdown-slide @@dashboard">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#!">카테고리<span><i class="fa fa-angle-down"></i></span>
                </a>

                <!-- Dropdown list -->
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item @@dashboardPage" href="dashboard.html">한식</a></li>
                    <li><a class="dropdown-item @@dashboardMyAds" href="dashboard-my-ads.html">중식</a></li>
                    <li><a class="dropdown-item @@dashboardFavouriteAds" href="dashboard-favourite-ads.html">일식</a></li>
                    
                    <li class="dropdown dropdown-submenu dropright">
                        <a class="dropdown-item dropdown-toggle" href="#!" id="dropdown0501" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">양식</a>
    
                        <ul class="dropdown-menu" aria-labelledby="dropdown0501">
                            <li><a class="dropdown-item" href="index.html">파스타</a></li>
                            <li><a class="dropdown-item" href="index.html">스테이크</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown dropdown-slide @@pages">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    지역 <span><i class="fa fa-angle-down"></i></span>
                </a>
                <!-- Dropdown list -->
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item @@about" href="about-us.html">About Us</a></li>
                    <li><a class="dropdown-item @@contact" href="contact-us.html">Contact Us</a></li>
                    <li><a class="dropdown-item @@profile" href="user-profile.html">User Profile</a></li>
                    <li><a class="dropdown-item @@404" href="404.html">404 Page</a></li>
                    <li><a class="dropdown-item @@package" href="package.html">Package</a></li>
                    <li><a class="dropdown-item @@singlePage" href="single.html">Single Page</a></li>
                    <li><a class="dropdown-item @@store" href="store.html">Store Single</a></li>
                    <li><a class="dropdown-item @@blog" href="blog.html">Blog</a></li>
                    <li><a class="dropdown-item @@singleBlog" href="single-blog.html">Blog Details</a></li>
                    <li><a class="dropdown-item @@terms" href="terms-condition.html">Terms &amp; Conditions</a></li>
                </ul>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto mt-10">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link login-button" href="/logout/">로그아웃</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link login-button" href="{% url 'users:user-login' %}">로그인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link login-button" href="{% url 'users:user-signup' %}">회원가입</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>